"""Self-contained mobile-first web chat for AIKA."""
CHAT_HTML = r'''<!doctype html>
<html lang="vi">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="color-scheme" content="dark">
<title>AIKA Chat</title>
<style>
:root{--bg:#111214;--panel:#191b1f;--muted:#9ca3af;--line:#2a2d33;--text:#f3f4f6;--bubble:#23262c;--accent:#f3f4f6}
*{box-sizing:border-box}html,body{height:100%;margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:var(--bg);color:var(--text)}
body{overflow:hidden}.app{height:100dvh;display:grid;grid-template-rows:56px 1fr auto;max-width:980px;margin:0 auto}
header{display:flex;align-items:center;justify-content:space-between;padding:0 14px;border-bottom:1px solid var(--line);background:rgba(17,18,20,.96)}
.brand{display:flex;align-items:center;gap:10px;font-weight:700}.dot{width:10px;height:10px;border-radius:50%;background:#22c55e;box-shadow:0 0 12px #22c55e80}
.actions{display:flex;gap:8px}button{font:inherit;color:var(--text);background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:8px 11px;cursor:pointer}button:disabled{opacity:.5;cursor:not-allowed}
#messages{overflow-y:auto;padding:22px 14px 34px}.empty{max-width:640px;margin:10vh auto 0;text-align:center;color:var(--muted)}.empty h1{font-size:30px;color:var(--text);margin-bottom:8px}
.msg{max-width:760px;margin:0 auto 18px;display:flex}.msg.user{justify-content:flex-end}.bubble{max-width:min(88%,720px);white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.55;padding:12px 14px;border-radius:16px;background:var(--bubble);border:1px solid var(--line)}
.user .bubble{background:#e5e7eb;color:#111827;border-color:#e5e7eb}.meta{font-size:12px;color:var(--muted);margin-top:8px}.error{color:#fecaca;border-color:#7f1d1d;background:#2b1517}
.generated{display:block;width:min(100%,640px);max-height:70vh;object-fit:contain;border-radius:14px;margin-top:10px;background:#0b0c0e;border:1px solid var(--line)}.download{display:inline-block;margin-top:10px;margin-right:8px;color:#fff;text-decoration:none;border:1px solid #4b5563;border-radius:10px;padding:7px 10px}.image-set{display:grid;gap:10px;margin-top:10px}
.composer{padding:10px 12px calc(10px + env(safe-area-inset-bottom));background:linear-gradient(180deg,transparent,var(--bg) 20%)}.composebox{max-width:780px;margin:0 auto;display:flex;align-items:flex-end;gap:8px;background:var(--panel);border:1px solid var(--line);border-radius:18px;padding:8px}
textarea{flex:1;resize:none;max-height:180px;min-height:44px;background:transparent;border:0;outline:0;color:var(--text);font:inherit;line-height:1.45;padding:11px 8px}.send{border-radius:12px;min-width:46px;height:44px;font-weight:700;background:var(--accent);color:#111;border-color:var(--accent)}
.status{max-width:780px;margin:5px auto 0;padding:0 8px;font-size:12px;color:var(--muted);min-height:16px}.typing{display:inline-flex;gap:5px}.typing i{width:6px;height:6px;border-radius:50%;background:#9ca3af;animation:pulse 1s infinite}.typing i:nth-child(2){animation-delay:.15s}.typing i:nth-child(3){animation-delay:.3s}@keyframes pulse{0%,80%,100%{opacity:.3}40%{opacity:1}}
dialog{width:min(92vw,420px);border:1px solid var(--line);border-radius:16px;background:var(--panel);color:var(--text);padding:18px}dialog::backdrop{background:#0009}label{display:block;font-size:13px;color:var(--muted);margin:12px 0 6px}input{width:100%;background:#101114;color:var(--text);border:1px solid var(--line);border-radius:10px;padding:11px;font:inherit}.row{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}.hint{font-size:13px;color:var(--muted);line-height:1.45}
@media(max-width:600px){header{padding:0 10px}.bubble{max-width:94%}}
</style>
</head>
<body>
<div class="app">
<header><div class="brand"><span class="dot"></span><span>AIKA</span></div><div class="actions"><button id="newChat">＋ Chat mới</button><button id="settings">⚙</button></div></header>
<main id="messages"></main>
<footer class="composer"><div class="composebox"><textarea id="input" rows="1" placeholder="Ra lệnh hoặc trò chuyện với AIKA..." aria-label="Tin nhắn"></textarea><button class="send" id="send">↑</button></div><div class="status" id="status"></div></footer>
</div>
<dialog id="connectDialog"><h3 style="margin:0 0 6px">Kết nối AIKA</h3><div class="hint">Nhập khóa truy cập của dự án. Khóa chỉ lưu trong phiên trình duyệt.</div><label for="token">AI_AGENT_API_TOKEN</label><input id="token" type="password" autocomplete="off"><div class="row"><button id="cancelConnect">Đóng</button><button id="saveConnect">Kết nối</button></div></dialog>
<script>
const $=s=>document.querySelector(s), messagesEl=$('#messages'), input=$('#input'), send=$('#send'), statusEl=$('#status'), dialog=$('#connectDialog'), tokenInput=$('#token');
const STORE='aika_chat_messages_v3', TOKEN='aika_chat_token_v1'; let messages=[], busy=false;
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function load(){const p=new URLSearchParams(location.hash.slice(1)),a=p.get('access');if(a)sessionStorage.setItem(TOKEN,a);try{messages=JSON.parse(localStorage.getItem(STORE)||'[]');if(!Array.isArray(messages))messages=[];}catch{messages=[];}render();if(!sessionStorage.getItem(TOKEN))dialog.showModal();}
function persist(){const safe=messages.slice(-80).map(m=>{const copy={...m};if(copy.imageUrl&&copy.imageUrl.startsWith('blob:'))copy.imageUrl='';if(Array.isArray(copy.imageUrls))copy.imageUrls=copy.imageUrls.map(u=>u&&u.startsWith('blob:')?'':u).filter(Boolean);return copy;});localStorage.setItem(STORE,JSON.stringify(safe));}
function renderImages(m){const urls=Array.isArray(m.imageUrls)&&m.imageUrls.length?m.imageUrls:(m.imageUrl?[m.imageUrl]:[]);if(!urls.length)return '';return '<div class="image-set">'+urls.map((url,i)=>'<div><img class="generated" src="'+esc(url)+'" alt="Ảnh '+(i+1)+' AIKA tạo"><a class="download" href="'+esc(url)+'" download="AIKA-image-'+(i+1)+'.png">Tải ảnh '+(i+1)+'</a></div>').join('')+'</div>';}
function render(){if(!messages.length){messagesEl.innerHTML='<div class="empty"><h1>AIKA</h1><div>Trò chuyện hoặc ra lệnh trực tiếp. Ví dụ: “AIKA tạo ảnh một cô gái châu Á...”</div></div>';return;}messagesEl.innerHTML=messages.map(m=>'<div class="msg '+esc(m.role)+'"><div class="bubble '+(m.error?'error':'')+'">'+esc(m.text)+renderImages(m)+(m.meta?'<div class="meta">'+esc(m.meta)+'</div>':'')+'</div></div>').join('');messagesEl.scrollTop=messagesEl.scrollHeight;}
function setBusy(v,label='AIKA đang xử lý...'){busy=v;send.disabled=v;input.disabled=v;statusEl.innerHTML=v?'<span class="typing"><i></i><i></i><i></i></span> '+esc(label):'';}
function sleep(ms){return new Promise(r=>setTimeout(r,ms));} function autoSize(){input.style.height='auto';input.style.height=Math.min(input.scrollHeight,180)+'px';}
function buildPrompt(){const recent=messages.filter(m=>!m.error).slice(-18);return 'Đây là cuộc trò chuyện trực tiếp với người dùng. Hãy trả lời tự nhiên bằng tiếng Việt trừ khi người dùng yêu cầu ngôn ngữ khác. Duy trì ngữ cảnh hội thoại.\n\n'+recent.map(m=>(m.role==='user'?'Người dùng':'AIKA')+': '+m.text).join('\n\n')+'\n\nAIKA:';}
function statusLabel(d){if(d.kind==='image'){if(d.worker_state==='starting')return 'Đang khởi động Image Worker cho AIKA...';if(d.worker_state==='ready'||d.worker_state==='idle')return 'AIKA đã sẵn sàng và đang nhận tác vụ ảnh...';if(d.worker_state==='busy')return 'AIKA đang tạo ảnh...';if(d.status==='processing'||d.status==='pending')return 'AIKA đang tạo ảnh bằng Image V2...';return 'AIKA đang xử lý ảnh...';}if(d.worker_state==='starting')return 'Đang khởi động Qwen cho AIKA...';if(d.status==='pending')return 'AIKA đang chờ worker...';if(d.status==='processing')return 'AIKA đang suy nghĩ...';return 'AIKA đang xử lý...';}
async function fetchGeneratedImage(url,token){const r=await fetch(url,{headers:{authorization:'Bearer '+token}});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.error||'Không tải được ảnh AIKA vừa tạo.');}return URL.createObjectURL(await r.blob());}
async function fetchGeneratedImages(urls,token){const out=[];for(const url of urls)out.push(await fetchGeneratedImage(url,token));return out;}
async function submit(){const text=input.value.trim();if(!text||busy)return;const token=sessionStorage.getItem(TOKEN);if(!token){dialog.showModal();return;}messages.push({role:'user',text});persist();render();input.value='';autoSize();setBusy(true,'AIKA đang nhận lệnh...');try{const start=await fetch('/v1/chat',{method:'POST',headers:{'content-type':'application/json','authorization':'Bearer '+token},body:JSON.stringify({message:text,prompt:buildPrompt()})});const started=await start.json().catch(()=>({}));if(!start.ok)throw new Error(start.status===401?'Khóa truy cập không đúng.':(started.detail||started.error||'AIKA không nhận được lệnh.'));const jobId=started.job_id;if(!jobId)throw new Error('AIKA không tạo được tác vụ.');setBusy(true,started.kind==='image'?'AIKA đã hiểu: tạo ảnh. Đang chuẩn bị Image V2...':'AIKA đang xử lý hội thoại...');let data=null;for(let i=0;i<360;i++){await sleep(2000);const r=await fetch('/v1/chat/status?job_id='+encodeURIComponent(jobId),{headers:{authorization:'Bearer '+token}});data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(r.status===401?'Khóa truy cập không đúng.':(data.detail||data.error||'Không đọc được trạng thái AIKA.'));setBusy(true,statusLabel(data));if(data.status==='done')break;if(data.status==='error')throw new Error(data.error||data.worker_error||'Tác vụ AIKA bị lỗi.');}if(!data||data.status!=='done')throw new Error('Tác vụ chạy quá lâu và đã dừng chờ trên giao diện.');if(data.kind==='image'&&data.has_image){const sourceUrls=Array.isArray(data.image_urls)&&data.image_urls.length?data.image_urls:[data.image_url];const imageUrls=await fetchGeneratedImages(sourceUrls,token);messages.push({role:'assistant',text:data.text||('AIKA đã tạo xong '+imageUrls.length+' ảnh.'),imageUrl:imageUrls[0]||'',imageUrls,meta:[data.provider,data.model,data.elapsed_seconds?Number(data.elapsed_seconds).toFixed(1)+'s':''].filter(Boolean).join(' · ')});}else{messages.push({role:'assistant',text:data.text||'',meta:[data.provider,data.model].filter(Boolean).join(' · ')});}persist();render();}catch(e){messages.push({role:'assistant',text:'Lỗi: '+e.message,error:true});persist();render();if(String(e.message).includes('Khóa truy cập'))dialog.showModal();}finally{setBusy(false);input.focus();}}
input.addEventListener('input',autoSize);input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit();}});send.addEventListener('click',submit);$('#settings').addEventListener('click',()=>{tokenInput.value='';dialog.showModal();tokenInput.focus();});$('#saveConnect').addEventListener('click',()=>{const v=tokenInput.value.trim();if(v){sessionStorage.setItem(TOKEN,v);dialog.close();input.focus();}});$('#cancelConnect').addEventListener('click',()=>dialog.close());$('#newChat').addEventListener('click',()=>{if(busy)return;messages=[];persist();render();input.focus();});load();autoSize();
</script>
</body>
</html>'''