create table if not exists public.ai_production_lessons (
  id bigint generated by default as identity primary key,
  task_type text not null,
  success boolean not null,
  failure_kind text,
  lesson text not null,
  config jsonb not null default '{}'::jsonb,
  metrics jsonb not null default '{}'::jsonb,
  evidence jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists ai_production_lessons_task_created_idx
  on public.ai_production_lessons (task_type, created_at desc);

alter table public.ai_production_lessons enable row level security;

revoke all on table public.ai_production_lessons from anon, authenticated;
grant select, insert on table public.ai_production_lessons to service_role;
